### ISSUE TITLE
db_upgrade.php

### ISSUE THREAD

**Issue by LeoRX** [surfrock66/torque#28]
Hi,..
Apologies in advance as I'm not very good with php or mysql.  after running db_upgrade it modified my tables to raw_logs_test_2019_04 from this line in db_upgrade.php.

 $new_table_name = "{$db_table}_test_{$suffix}";

Should it be  $new_table_name = "{$db_table}_{$suffix}" ?

Cheers

**Comment by surfrock66** [comment]
Yes you're right, that was left in from my internal testing, lemme push an update.

**Comment by surfrock66** [comment]
Push committed, should be fixed.
