### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by arduiacob** [surfrock66/torque#34]
Google ask for money $ for the use of Google Maps.  How about a change to OpenStreetMaps?

**Comment by surfrock66** [comment]
I'm not opposed to that, but to be honest I don't have time to code much anymore.  If you want to fork or submit a pull request I'm totally open to it.

**Comment by mo5245** [comment]
#41 set `$use_OSM` to true and will use OpenStreetMap with map tiles by Stamen Design. at some point might try MapBox and Thunderforest for map tiles as both have decent free tier.
