### ISSUE TITLE
Error with upload_data.php

### ISSUE THREAD

**Issue by xerion3800** [surfrock66/torque#38]
When i start the upload from the app tot the server i get the follow error.log from apach2:

[Thu Feb 18 20:22:19.267418 2021] [php7:warn] [pid 21433] [client 192.168.178.40:45834] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, string given in /var/www/html/torque/upload_data.php on line 10

**Comment by surfrock66** [comment]
Did you get that fixed?  To be honest, since the pandemic I haven't used this at all since the ODBII adapter was draining my battery as I no longer drive anywhere.  Was it a bug?

**Comment by xerion3800** [comment]
Sorry for confusing. It was more than  less a problem on my repository site.
