### ISSUE TITLE
GRANT USAGE, FILE TO 'steve'@'localhost'; Error

### ISSUE THREAD

**Issue by xXAzazelXx** [surfrock66/torque#5]
Hey guys,

Im very new to this and dont know SQL :(

When i follow your guide and at very start when i try to create database I get the same error.

GRANT USAGE, FILE TO 'azazel'@'localhost';

mysql> GRANT USAGE, FILE 'azazel'@'localhost';

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''azazel'@'localhost'' at line 1

Everything above worked fine.

mysql> CREATE DATABASE torque;
Query OK, 1 row affected (0.24 sec)

mysql> CREATE USER 'azazel'@'localhost' IDENTIFIED BY 'blablabla';
Query OK, 0 rows affected (0.00 sec)

Any ideas? :)

**Comment by aldodemi** [comment]
for those like you, and me at my first try, that don't have any other database, try instead to use:
GRANT ALL ON *.* TO ‘azazel’@’localhost’;

**Comment by xXAzazelXx** [comment]
mysql> GRANT ALL ON . TO ‘azazel’@’localhost’;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TO ‘azazel’@’localhost’' at line 1



No Sorry, this is what I'm getting

**Comment by aldodemi** [comment]
Sorry lost something.....
the correct command is with stars/asterisks:
GRANT ALL ON *.* TO ‘azazel’@’localhost’;

**Comment by aldodemi** [comment]
don't understand why stars/asterisks are removed, try again:
"GRANT ALL ON *.* TO ‘azazel’@’localhost’;"

**Comment by aldodemi** [comment]
no way to show the stars asterisks......
by the way: GRANT ALL ON "star"."star" TO ‘azazel’@’localhost’;
also look at the torque forum https://torque-bhp.com/forums/?wpforumaction=viewtopic&t=7617.0

**Comment by xXAzazelXx** [comment]
mysql> GRANT ALL ON *.* TO ‘azazel’@’localhost’;
Query OK, 0 rows affected (0.00 sec)


Thank you :)
