### ISSUE TITLE
Fresh install css fails to load

### ISSUE THREAD

**Issue by oisac** [surfrock66/torque#55]
I cloned the repo on a fresh linode instance and no formatting or css is loading. I also run this repo at Dreamhost with no issues at all. Is there something that needs to be configured for PHP on linode that I'm missing?

I'm using PHP 7.4-FastCGI and Apache 2.4.52 on Ubuntu 22.04 LTS. Logging works fine to a dedicated MySql 5.7.30 server.

**Comment by surfrock66** [comment]
No clue, I have never run anything on linode, but there shouldn't be anything special, this is a pretty simple app.  If you view source on the main page, and find the link to the css file, can you click/load it?

**Comment by oisac** [comment]
I did view source and all links go to the specified file. I have no idea what the issue is. I'm going to try reinstalling apache. Dreamhost is shared hosting so I just cloned and all was good, I don't have access to any apache/php configs.

**Comment by oisac** [comment]
Nuked my server and started over. Looks like I missed something in the initial apache/php install even though other php stuff worked. All is good now. Issue resolved.

**Comment by surfrock66** [comment]
Glad it worked, enjoy!
